apiVersion: v1
kind: Namespace
metadata:
  name: ingress-ns
  labels:
    cert-manager.io/disable-validation: "true"


---

apiVersion: v1
kind: Namespace
metadata:
  name: akv2k8s
  labels:
    cert-manager.io/disable-validation: "true"
