apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testingress
  namespace: certsync
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - api.gr1.froissant.work
    secretName: nginx-cert
  rules:
  - host: api.gr1.froissant.work
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80
              
