apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image:  ghcr.io/projet-infra-orleans/pandemic-infra/app:main
        ports:
        - containerPort: 80
      imagePullSecrets: 
      - name: github-packages-secret
  