apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-pass: "http://app-service"
spec:
  # ingressClassName: nginx
  # tls:
  # - hosts:
  #   - {{ .Values.ingress.host }}
  #   secretName: tls-secret
  rules:
    - host: gr1.froissant.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-service
