apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-url-mongo-db
  namespace: default
spec:
  vault:
    name: gr1-az-key-vault # name of key vault
    object:
      name: ${dns}-mongo-url # name of the akv object
      type: secret # akv object type
  output:
    secret:
      name: mongo-url # kubernetes secret name
      dataKey: secret-mongo-url # key to store object value in kubernetes secret

