apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-deployment
  template:
    # annotations:
    #   vault.hashicorp.com/agent-inject: "true"
    #   vault.hashicorp.com/role: "internal-app"
    #   vault.hashicorp.com/agent-inject-secret-database-config.txt: "internal/data/database/config"
    metadata:
      labels:
        app: api-deployment
    spec:
      # serviceAccountName: internal-app
      volumes:
        - name: logs-pv-storage
          persistentVolumeClaim:
            claimName: logs-pv-claim
      containers:
        - name: api
          image: ghcr.io/projet-infra-orleans/pandemic-infra/api:main
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/api/data"
              name: logs-pv-storage
          limit:
            memory: 1Go
      imagePullSecrets:
        - name: github-packages-secret
