apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      volumes:
        - name: logs-pv-storage
          persistentVolumeClaim:
            claimName: logs-pv-claim
      containers:
        - name: api
          image: ghcr.io/projet-infra-orleans/pandemic-infra/api:v3.1.1
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/api/data"
              name: logs-pv-storage
          limit:
            memory: 1Go
          env:
            - name: DATABASE_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-url
                  key: secret-mongo-url
            - name: CLIENT_URL
              value: https://app.${dns}
      imagePullSecrets:
        - name: github-packages-secret
