apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
 volumes:
    - name: logs-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image:  ghcr.io/projet-infra-orleans/pandemic-infra/api:main
        ports:
        - containerPort: 8080
      imagePullSecrets: 
      - name: github-packages-secret
  
