apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      volumes:
      - name: logs-pv-storage
        persistentVolumeClaim:
          claimName: logs-pv-claim
      containers:
      - name: api
        image:  ghcr.io/projet-infra-orleans/pandemic-infra/api:main
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/api/data"
          name: logs-pv-storage
      imagePullSecrets: 
      - name: github-packages-secret
     
  
