apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: api-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-api
    nginx.ingress.kubernetes.io/proxy-pass: "http://api-service:8080"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.gr1.froissant.work
      secretName: tls-secret
  rules:
    - host: api.gr1.froissant.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  name: http
